name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/capeisti/infinite-grid-demo:latest

    - name: Test
      run: mvn -P it,production verify

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push
      run: |
        docker push ghcr.io/capeisti/infinite-grid-demo:latest